### ISSUE TITLE
Switch Accounts

### ISSUE THREAD

**Issue by KmanProdz** [komefai/PS4Macro#12]
Is it possible to use this tool to log out of PSN account on PS4 and change/log into another account one. without having to restarting remote play tool?

**Comment by komefai** [comment]
It's technically possible to automate the login process of PS4 Remote Play. However, since they implemented recaptcha into their login system, then you would have to find a way to solve it. I understand what you're trying to do here, but because the recaptcha implementation can be changed in the future I decided to not have this feature at all.

My suggestion is to implement this feature within your script instead, either by cracking the captcha by bruteforce or by patching the Remote Play executable to bypass it entirely.
