### ISSUE TITLE
Unable to start script

### ISSUE THREAD

**Issue by Nikkor89** [komefai/PS4Macro#2]
Hi. I'm writing heres since I don't really know where to report this problem.
Today I've downloaded your app and followed your tutorial to script a simple code as a test but when I tried to start it in the program i got this window
![screenshot 7](https://user-images.githubusercontent.com/32204872/30758088-4ac815aa-9fd1-11e7-95c1-4127b6557304.png)
I'm new to coding but the script was pretty simple, just a few button pressings without conditions. if needed I can load it here.
ps: I've only tried on one pc so I can't exclude the problem is mine, but I didn't have the time to test it elsewhere today.

**Comment by komefai** [comment]
You are at the right place to report the problem :)

The error happens when PS4Macro couldn't detect the panel that were used to render the graphics in Remote Play. By default the program looks for a control with a `WindowsForms10.Window.8.app.0.141b42a_r9_ad1` class. You can confirm this by using Spy++.

Here are the steps:

1. Launch RemotePlay and start the connection
2. In Visual Studio go to Tools->Spy++
3. Click on Find Window (binoculars icon)
4. Click on the crosshair icon and drag/drop to PS4 Remote Play
5. Confirm the `Class:` value

![Steps](https://user-images.githubusercontent.com/30201667/30759003-b4e861ba-9ffe-11e7-8dd8-d40fabaaf26f.png)

Let me know what you got from that box so we can investigate further.

**Comment by Nikkor89** [comment]
here I am. this is what I got from the steps.
ah. if it can help I'm using Windows 10
WindowsForms10.Window.8.app.0.141b42a_r10_ad1

**Comment by komefai** [comment]
Thank you for your report! I've fixed this problem in [this commit](https://github.com/komefai/PS4Macro/commit/9814d884e5d702835309e9e3c85b84ed66f84354).

You can either recompile PS4Macro from source or download this fixed PS4MacroAPI.dll and replace it in your existing PS4Macro folder.

[PS4MacroAPI_9814d884.zip](https://github.com/komefai/PS4Macro/files/1326406/PS4MacroAPI_9814d884.zip)
