### ISSUE TITLE
Not enough memory

### ISSUE THREAD

**Issue by Zulo2012** [komefai/PS4Macro#23]
Hi Komefai I  don't know why when detecting some areas I get "out of memory" error, or maybe the macro is working as intended and when the screen changes: error. Do you have any Ideas why some rectmaps are working and others don't for me?
Also why when I turn start play on the macro my remote play gets out of fullscreen? Is this optional?

Congrats on the great job and regards.

**Comment by komefai** [comment]
Hi, the Out of memory error is thrown when you're trying to crop and image to a larger size than the size of the image itself. To avoid this, you have to come up with the resolution that you want and stick with it. This is also why it has to resize when you press the play button. The default size is 1024x768. You can change it by setting this in your script's config (in the constructor):

```csharp
Config.Name = "Example Script";
// 1080p
Config.TargetSize = new Size(1920, 1080);
```

This however is just resizing the window and does not make it fullscreen. Using PS4 Remote Play on fullscreen with scripting is highly not recommended because a full screen on one machine does not equal to the full screen resolution on another machine, so please keep that in mind when designing your RectMaps. 

There are plans to intercept the graphics directly from the PS4 in the future so the window size / screen resolution won't be a problem then. But sadly, this is the only way for now.

Thanks for the kind words :)

**Comment by Zulo2012** [comment]
Hi, I managed to make some functions work flawlessly on my developement computer, but when I try to use the same program on a barebone I have, the screenshot resolution has changed and the rectmap do not work. 
In my developement computer if I set the targetSize to 1024x768 the screenshots are 1008x721, and in my barebone they are 1008x729, and I have also checked the screen elements size and it is different, so I cannot change the coordenates.
Any Idea why is this happening?
Thanks
