### ISSUE TITLE
Current Image size

### ISSUE THREAD

**Issue by bbday** [komefai/PS4Macro#32]
I have issue when try to display/save CurrentFrame the size it is wrong (i tried to use 720p a 520p resolution the size it is always the same). 
If i try to resize RP window it will zoom in/out. (property of size currentFrame are always width:1265 height:683) I don't understand why it get this size.

screen:
https://ibb.co/itqCwT

Also with Screenshot button on menu same issue.

Then can't work plugins cause it will miss information from image

I also download precompiled version and make a screenshot from menu, same issue.

**Comment by KaruroHNS** [comment]
Hmmm i dont have probem with the resolution, but i dont play watching the PS4 remote play because its so laggy with my keyboard, i think is better play watching the HDMI out  from your TV connected to PS4 instead playing in the PC.
I hope you find a solution. Luck.

psdt: Sorry, i dont know a lot of english :"v

**Comment by bbday** [comment]
Sorted, was dpi resize problem

**Comment by mattriecken** [comment]
@bbday How did you fix the dpi problem?
