### ISSUE TITLE
playmacro() play twice & how press 2 button at same time

### ISSUE THREAD

**Issue by Gnoxidez** [komefai/PS4Macro#9]
playmacro()Command play twice if emulateController
my game need to press R1 L1 at same time to activate

**Comment by komefai** [comment]
Hi, are you using version 0.5.1? Because the macro player now has looping disabled by default when using in a script.

To press multiple buttons at a time you can do this:

```csharp
script.Press(new DualShockState() { R1 = true, L1 = true }, 100);
```

**Comment by Gnoxidez** [comment]
thank i will update

**Comment by clempe** [comment]
[I think you want something like this?](https://github.com/komefai/PS4Macro/issues/5)

**Comment by Gnoxidez** [comment]
macro record from PS4 Controller
replay well 
but if emulate it do haft 
ex. 
PS4 Controller : walk 10 unit > turn left 10
Emulate Controller : walk 5 unit > turn left (maybe same)

can u test this ?

**Comment by komefai** [comment]
Thanks for the report! I can also confirm that the macros are playing much faster when emulating the controller. It becomes very noticeable when the macro is long (I've tested it on a macro with 35726 frames).

I decided to measure the execution time of the actual I/O read on the real controller and it turns out to have a delay of 1ms (or no delay at all sometimes). So I added a constant 1ms delay to compensate the speed when using controller emulation and my macro seems to be working at the correct speed now.

You can wait for the fix in the official release or try this fix right now by replacing `PS4RemotePlayInterceptor.dll` in the folder (don't forget to keep the old copy) with this one:

[PS4RemotePlayInterceptor.dll - Temp Fix](https://github.com/komefai/PS4Macro/files/1625799/PS4RemotePlayInterceptor_DEBUG_Compensate_Read.zip)

**Comment by Gnoxidez** [comment]
emulate +  script.Press(new DualShockState() { RX = (byte)191 }, 500);
don't work ?

**Comment by komefai** [comment]
You should try 0 or 255 instead. Please create a new issue because this issue is closed and it is unrelated to your original issue.
